spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to PDL Bank accounts related QA APIs "
  contactDetails:
    name: "Janeen Faye Umandap-Lorenzo - QA Head"
    email: "janeenfaye@pdlorenzo.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371